name: "     (🟣 Rollback) Crear Variable en Dev/UAT │ Revertir de Azure y cambio de Pull Request"

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "1.1.2 Rollback (dev/uat) - Create App Setting"
