name: "    (🟠 Rollback) Crear Variable (PRD) │ Revertir cambio de Pull Request"

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "1.2.2 Rollback (prd) - Create Variable PR"
